"""Tesis YURAKU de Christian Flores y Franklin Villavicencio 2019"""

"""
Django settings for YURAKU project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w4u0_l3(bnkyw9-pdj$656lzj&wod+a@#mf05&4$fb^fyd-c-!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.128', '192.168.137.160', '172.16.218.64', '192.168.1.11','0.0.0.0']
#ALLOWED_HOSTS = ['franklin.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
    'social_django',
    'rest_framework',
    'gestionplantas',
    'gestionperfil',
    'gestionbusqueda',
    'chartjs',
    'gestionreconocimiento',
    'gestionresultado',
    'gestioncomentario',
    'gestionjuego',
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'YURAKU.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'YURAKU.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'YURAKU',
        'USER': 'YURAKU',
        'PASSWORD': 'Yuraku',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        #'NAME': 'yuraku',
        #'USER': 'yuraku',
        #'PASSWORD': 'Yuraku',
        #'HOST': 'franklin-1276.postgres.pythonanywhere-services.com',
        #'PORT': '11276',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL= reverse_lazy('login')

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es-sp'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

TEMPLATE_DIRS = (os.path.join(BASE_DIR,  'templates'),)

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'villa.chispo@gmail.com'
#EMAIL_HOST_USER = 'yuraku2019@gmail.com'
EMAIL_HOST_PASSWORD= 'Frn14k9542@@'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


LOGIN_REDIRECT_URL = 'homepage'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '604096279264-9vveool58nvipkh9vq59f3t8nr849fim.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'k6IHijbWBU-DwyXApEuSfYsq'

SOCIAL_AUTH_GITHUB_KEY ='ee0d76d261070bcb8e10'
SOCIAL_AUTH_GITHUB_SECRET = '0f52ff30a45ce825af28bdb8200d3e5b6066c822'

#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '573942488723-6jgjqneq56k25u41ic9nusok89tq7lfa.apps.googleusercontent.com'
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Hm3SCjlnSLsvCh67XXKm22G6'

#SOCIAL_AUTH_GITHUB_KEY = 'bff4d54eafc9650b37ee'
#SOCIAL_AUTH_GITHUB_SECRET = 'a0ca5db081e8988381bd61578286144a0d3d135b'